### PR TITLE
Fix README toc anchor link

### PR DESCRIPTION
**Pull request by TristanCacqueray**
This change makes the tutorial table of content link clickable.

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Not sure why the link was like that, but the trailing `-` makes click event noop.

**Comment by chshersh** [comment]
@TristanCacqueray They are written this way intentionally to be clickable on GitHub. I can see them working if I click them from the `REAME.md` on GitHub. If I go to your repository and try to click the links, I can see that they don't work anymore. Can you provide more details on the issue you observe?

**Comment by TristanCacqueray** [comment]
Oh I see it is working as expected in the GitHub project rendering. However in the github pages ( https://kowainik.github.io/projects/relude ), then it doesn't work for me, at least with firefox.

**Comment by vrom911** [comment]
@TristanCacqueray yeah, this is unfortunate ambiguous behaviour for links at GitHub vs Pandoc. I have created the issue https://github.com/kowainik/kowainik.github.io/issues/117 to fix it on the website side, as the proposed in this PR changes will break linking at GitHub (yes, this is some complicated technology, I know :smile: )

**Comment by TristanCacqueray** [comment]
I see, this seems caused by the `↑` link. Thanks!

**Comment by vrom911** [comment]
FYI, this is fixed now :tada:

**Pull request closed without merging**
