### PR TITLE
[#80] Adds hlint rules for whenLeft and whenRight

### LINKED ISSUE #80: Add hlint rules for `whenLeft` and `whenLeftM`
Also `whenRight` and `whenRightM` can be done here.

### PR DESCRIPTION
**Pull request by JasonMFry**
Resolves #80

And their monadic versions. Simply copied and pasted pre-existing rules
for whenLeft_, whenRight_, and _their_ monadic versions.

### HLint

- [ ] I've changed the exposed interface (add new reexports, remove reexports, rename reexported things, etc.).
  - [x] I've updated [`hlint.dhall`](https://github.com/kowainik/relude/blob/master/hlint/hlint.dhall)
        accordingly to my changes (add new rules for the new imports, remove old ones, when they are outdated, etc.).
  - [x] I've generated the new `.hlint.yaml` file (see 
        [this instructions](https://github.com/kowainik/relude#generating-hlintyaml)).

### General

- [ ] I've updated the [CHANGELOG](https://github.com/kowainik/relude/blob/master/CHANGELOG.md) 
      with the short description of my latest changes.
- [x] All new and existing tests pass.
- [x] I keep the code style used in the files I've changed (see 
      [style-guide](https://github.com/kowainik/org/blob/master/style-guide.md#haskell-style-guide) 
      for more details).
- [ ] I've used the [`stylish-haskell` file](https://github.com/kowainik/relude/blob/master/.stylish-haskell.yaml).
- [x] My change requires the documentation updates.
  - [x] I've updated the documentation accordingly.
- [ ] I've added the `[ci skip]` text to the docs-only related commit's name.

### CODE REVIEW

**Comment by JasonMFry** [comment]
@vrom911 thanks for the guidance, I'll address this soon, maybe during lunch.

**Comment by JasonMFry** [comment]
Would you prefer me to create a new branch, that way the reverted commit isn't merged?

**Comment by vrom911** [comment]
@JasonMFry No need to create a new branch, it's okay this way 🙂 

How is it going with my comments, do you need any clarification/help on that?

**Comment by vrom911** [comment]
Seems like you don't have time for this. No worries!

We are going to make a new release and for that we need this issue to be done, so we will make it in another PR as there is no way for us to push to your branch. 

Thanks for your help anyway ❤️ If you'd like to contribute in the future just let us know, we will be glad to collaborate with you!

**Comment by ChShersh** [comment]
@JasonMFry @vrom911 This was resolved in the PR #120 so I'm closing this PR.

**Comment by JasonMFry** [comment]
@vrom911 thanks for understanding, I found myself with very little time :(

**Pull request closed without merging**
